# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sandi/http

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sandi/http

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sandi/http/CMakeFiles /home/sandi/http/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sandi/http/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named simpleHttpServer2

# Build rule for target.
simpleHttpServer2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simpleHttpServer2
.PHONY : simpleHttpServer2

# fast build rule for target.
simpleHttpServer2/fast:
	$(MAKE) -f CMakeFiles/simpleHttpServer2.dir/build.make CMakeFiles/simpleHttpServer2.dir/build
.PHONY : simpleHttpServer2/fast

HttpMessage.o: HttpMessage.cpp.o

.PHONY : HttpMessage.o

# target to build an object file
HttpMessage.cpp.o:
	$(MAKE) -f CMakeFiles/simpleHttpServer2.dir/build.make CMakeFiles/simpleHttpServer2.dir/HttpMessage.cpp.o
.PHONY : HttpMessage.cpp.o

HttpMessage.i: HttpMessage.cpp.i

.PHONY : HttpMessage.i

# target to preprocess a source file
HttpMessage.cpp.i:
	$(MAKE) -f CMakeFiles/simpleHttpServer2.dir/build.make CMakeFiles/simpleHttpServer2.dir/HttpMessage.cpp.i
.PHONY : HttpMessage.cpp.i

HttpMessage.s: HttpMessage.cpp.s

.PHONY : HttpMessage.s

# target to generate assembly for a file
HttpMessage.cpp.s:
	$(MAKE) -f CMakeFiles/simpleHttpServer2.dir/build.make CMakeFiles/simpleHttpServer2.dir/HttpMessage.cpp.s
.PHONY : HttpMessage.cpp.s

HttpRequest.o: HttpRequest.cpp.o

.PHONY : HttpRequest.o

# target to build an object file
HttpRequest.cpp.o:
	$(MAKE) -f CMakeFiles/simpleHttpServer2.dir/build.make CMakeFiles/simpleHttpServer2.dir/HttpRequest.cpp.o
.PHONY : HttpRequest.cpp.o

HttpRequest.i: HttpRequest.cpp.i

.PHONY : HttpRequest.i

# target to preprocess a source file
HttpRequest.cpp.i:
	$(MAKE) -f CMakeFiles/simpleHttpServer2.dir/build.make CMakeFiles/simpleHttpServer2.dir/HttpRequest.cpp.i
.PHONY : HttpRequest.cpp.i

HttpRequest.s: HttpRequest.cpp.s

.PHONY : HttpRequest.s

# target to generate assembly for a file
HttpRequest.cpp.s:
	$(MAKE) -f CMakeFiles/simpleHttpServer2.dir/build.make CMakeFiles/simpleHttpServer2.dir/HttpRequest.cpp.s
.PHONY : HttpRequest.cpp.s

HttpResponse.o: HttpResponse.cpp.o

.PHONY : HttpResponse.o

# target to build an object file
HttpResponse.cpp.o:
	$(MAKE) -f CMakeFiles/simpleHttpServer2.dir/build.make CMakeFiles/simpleHttpServer2.dir/HttpResponse.cpp.o
.PHONY : HttpResponse.cpp.o

HttpResponse.i: HttpResponse.cpp.i

.PHONY : HttpResponse.i

# target to preprocess a source file
HttpResponse.cpp.i:
	$(MAKE) -f CMakeFiles/simpleHttpServer2.dir/build.make CMakeFiles/simpleHttpServer2.dir/HttpResponse.cpp.i
.PHONY : HttpResponse.cpp.i

HttpResponse.s: HttpResponse.cpp.s

.PHONY : HttpResponse.s

# target to generate assembly for a file
HttpResponse.cpp.s:
	$(MAKE) -f CMakeFiles/simpleHttpServer2.dir/build.make CMakeFiles/simpleHttpServer2.dir/HttpResponse.cpp.s
.PHONY : HttpResponse.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/simpleHttpServer2.dir/build.make CMakeFiles/simpleHttpServer2.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/simpleHttpServer2.dir/build.make CMakeFiles/simpleHttpServer2.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/simpleHttpServer2.dir/build.make CMakeFiles/simpleHttpServer2.dir/main.cpp.s
.PHONY : main.cpp.s

simpleHttpServer.o: simpleHttpServer.cpp.o

.PHONY : simpleHttpServer.o

# target to build an object file
simpleHttpServer.cpp.o:
	$(MAKE) -f CMakeFiles/simpleHttpServer2.dir/build.make CMakeFiles/simpleHttpServer2.dir/simpleHttpServer.cpp.o
.PHONY : simpleHttpServer.cpp.o

simpleHttpServer.i: simpleHttpServer.cpp.i

.PHONY : simpleHttpServer.i

# target to preprocess a source file
simpleHttpServer.cpp.i:
	$(MAKE) -f CMakeFiles/simpleHttpServer2.dir/build.make CMakeFiles/simpleHttpServer2.dir/simpleHttpServer.cpp.i
.PHONY : simpleHttpServer.cpp.i

simpleHttpServer.s: simpleHttpServer.cpp.s

.PHONY : simpleHttpServer.s

# target to generate assembly for a file
simpleHttpServer.cpp.s:
	$(MAKE) -f CMakeFiles/simpleHttpServer2.dir/build.make CMakeFiles/simpleHttpServer2.dir/simpleHttpServer.cpp.s
.PHONY : simpleHttpServer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... simpleHttpServer2"
	@echo "... HttpMessage.o"
	@echo "... HttpMessage.i"
	@echo "... HttpMessage.s"
	@echo "... HttpRequest.o"
	@echo "... HttpRequest.i"
	@echo "... HttpRequest.s"
	@echo "... HttpResponse.o"
	@echo "... HttpResponse.i"
	@echo "... HttpResponse.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... simpleHttpServer.o"
	@echo "... simpleHttpServer.i"
	@echo "... simpleHttpServer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

